using System;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Navigation;

namespace yanshuai
{
    public sealed partial class InfoPage : Page
    {
        public InfoPage() { InitializeComponent(); }

        protected override void OnNavigatedTo(NavigationEventArgs e)
        {
            base.OnNavigatedTo(e);
            AppSettings.ApplyTheme(RootGrid, this);
            ApplyLanguage();
        }

        private void ApplyLanguage()
        {
            AppTitle.Text = AppSettings.S("言枢 AI", "言枢 AI");
            AppSubtitle.Text = AppSettings.S("AI 对话助手 · 适配 Windows 10 Mobile", "AI Chat Assistant · Windows 10 Mobile");
            DisclaimerHeader.Text = AppSettings.S("免责声明", "Disclaimer");
            DisclaimerContent.Text = AppSettings.S("言枢 AI 所提供的对话内容由第三方大语言模型生成，不代表开发者立场。AI 的输出可能存在错误、偏差或不完整的情况，请自行判断其准确性，不应将其作为专业建议的依据。",
                "Content is generated by third-party LLMs and does not reflect the developer's views. AI outputs may contain errors. Use at your own discretion.");
            TermsHeader.Text = AppSettings.S("使用条款", "Terms of Use");
            TermsContent.Text = AppSettings.S("• 本软件仅供个人学习与研究使用，禁止用于任何违反法律法规的用途。\n• 用户对通过本软件发起的对话内容及其后果承担全部责任。\n• 本软件不存储、不上传用户的对话内容，所有数据仅保存在本机设备上。\n• API 密钥由用户自行配置和管理，开发者不对密钥泄露或滥用负责。",
                "• For personal learning and research only. Illegal use prohibited.\n• Users assume full responsibility for their conversations.\n• This app does not store or upload conversation data. All data stays local.\n• API keys are user-managed. Developer is not responsible for leaks or misuse.");
            PrivacyHeader.Text = AppSettings.S("隐私说明", "Privacy Policy");
            PrivacyContent.Text = AppSettings.S("本软件不收集任何用户数据，不包含任何遥测或统计功能。对话记录、API 配置等全部信息均以本地文件形式存储于设备上，不会被发送至任何服务器（API 请求除外，该请求由用户自行配置的端点处理）。",
                "This app collects no user data and contains no telemetry. Chat history, API configs, and all data are stored locally and never sent to any server (except API requests to your configured endpoint).");
            VersionHeader.Text = AppSettings.S("版本", "Version");
            VersionText.Text = AppSettings.S("言枢 AI  ·  2.0.0.0", "言枢 AI  ·  2.0.0.0");
            TargetPlatformLabel.Text = AppSettings.S("目标平台：Windows 10 10240 (Mobile)", "Target: Windows 10 10240 (Mobile)");
            DevHeader.Text = AppSettings.S("开发者", "Developer");
            DevDesc.Text = AppSettings.S("成分复杂", "Complicated");
            DevMotto.Text = AppSettings.S("\"点击输入文本\"", "\"Click to enter text\"");
            ChangelogHeader.Text = AppSettings.S("更新日志", "Changelog");

            ApplyChangelogLanguage();
        }

        private void ApplyChangelogLanguage()
        {
            V200Header.Text = AppSettings.S("v2.0.0  ·  九皋  ·  2026", "v2.0.0  ·  Nine Heights  ·  2026");
            V150Header.Text = AppSettings.S("v1.5.0  ·  2026", "v1.5.0  ·  2026");
            V140Header.Text = AppSettings.S("v1.4.0  ·  2026", "v1.4.0  ·  2026");
            V133Header.Text = AppSettings.S("v1.3.3  ·  2026", "v1.3.3  ·  2026");
            V132Header.Text = AppSettings.S("v1.3.2  ·  2026", "v1.3.2  ·  2026");
            V131Header.Text = AppSettings.S("v1.3.1  ·  2026", "v1.3.1  ·  2026");
            V130Header.Text = AppSettings.S("v1.3.0  ·  2026", "v1.3.0  ·  2026");
            V120Header.Text = AppSettings.S("v1.2.0  ·  2026", "v1.2.0  ·  2026");
            V110Header.Text = AppSettings.S("v1.1.0", "v1.1.0");
            V100Header.Text = AppSettings.S("v1.0.0  ·  首发", "v1.0.0  ·  Initial Release");

            V200Bullets.Text = AppSettings.S("• ShellPage 统一导航架构：全局汉堡菜单状态保持、统一定位与返回按钮\n• 品牌色系统全面启用：珊瑚橙主题（RoleplayTheme）加载生效，导航按钮获悬停/按下交互反馈\n• 角色卡页面重构：按分组折叠展开、卡片内联展开显示「详细信息」「新对话」按钮、多选模式与批量删除\n• 外观设置控件统一：ColorPresetPanel 组件复用，减少布局重复代码\n• 汉堡菜单优化：用户头像动态展示、当前用户名称动态更新、等宽导航按钮、底部留白避免 CommandBar 遮挡\n• 全局返回按钮（ShellPage 顶栏 + 各页 CommandBar 补全）\n• 图标不透明度资源化统一管理\n• ToggleSwitch 布局修复：移除负边距 hack\n• 清理未使用存根代码（ChatMessage / ChatSession / SessionManager / StartPage / ChatHistoryPage）\n• 启动行为导航适配 ShellPage 架构",
                "• ShellPage unified nav: global hamburger state, unified back\n• Coral orange theme with hover/press feedback on nav buttons\n• Character card page: group collapse/expand, inline detail/new-chat buttons, multi-select\n• Unified ColorPresetPanel appearance control\n• Dynamic avatar/name in hamburger menu, uniform nav buttons\n• Global back button (ShellPage + all CommandBars)\n• Icon opacity resource management\n• ToggleSwitch negative-margin hack removed\n• Cleaned up unused stub code\n• Startup nav adapted to ShellPage");

            V150Bullets.Text = AppSettings.S("• 世界书支持树形分组，点击组头可折叠/展开\n• 对话列表、角色卡、世界书多选模式全面重写：右键/长按进入，复选框样式修复\n• 修复竖向图片压缩撕裂问题\n• 修复删除对话后 Mobile 软键盘意外弹起\n• 角色卡导入改为文件选择器，不再跳转相册\n• API Key 支持长按眼睛图标预览",
                "• World Book tree groups, collapsible headers\n• Multi-select rewrite for all lists: right-tap/long-press, checkbox fix\n• Fixed vertical image compression tear\n• Fixed mobile keyboard popup on conversation delete\n• Card import uses file picker (no more gallery)\n• API Key peek on long-press eye icon");

            V140Bullets.Text = AppSettings.S("• 思考过程标签动态化：流式推理期间显示随机动态词（Thinking / Pondering / Reflecting 等），结束后恢复为「思考过程」\n• 设置页新增「回复声音」开关，可关闭 AI 回复完成提示音\n• 设置页新增「默认展开思考过程」开关\n• 多对话并行后台生成：切换对话时生成任务不中断，返回后自动恢复流式显示",
                "• Dynamic thinking label: random verbs during streaming, restores after\n• Reply Sound toggle in settings\n• Auto-expand reasoning toggle in settings\n• Parallel multi-conversation generation: streaming survives tab switch");

            V133Bullets.Text = AppSettings.S("• Bug fix\n• 性能优化\n• 移除了 Herobrine",
                "• Bug fix\n• Performance\n• Removed Herobrine");

            V132Bullets.Text = AppSettings.S("• Bug fix\n• 性能优化\n• 移除了 Herobrine",
                "• Bug fix\n• Performance\n• Removed Herobrine");

            V131Bullets.Text = AppSettings.S("• Bug fix\n• 性能优化\n• 移除了 Herobrine",
                "• Bug fix\n• Performance\n• Removed Herobrine");

            V130Bullets.Text = AppSettings.S("• 对话列表 / 角色卡列表支持置顶与分组\n• 右键（PC）/ 长按（手机）直接进入多选模式\n• 角色卡新建/编辑改为 4 步全页面向导\n• 角色卡完整支持 ST V2 扩展字段：系统提示词、历史后注入、示例对话、作者信息等\n• 导入导出完整还原上述字段，PNG 卡格式兼容\n• 角色卡置顶按钮加入多选操作栏",
                "• Pin & group for conversation/character lists\n• Right-click (PC) / long-press (mobile) multi-select\n• 4-step full-page character card wizard\n• Full ST V2 extended fields: system prompt, post-history, examples\n• Import/export preserves all fields, PNG card compatible\n• Pin button in multi-select toolbar");

            V120Bullets.Text = AppSettings.S("• OOBE 初始引导向导（API / 角色卡 / 用户资料）\n• 角色卡新建向导（3步式全页面）\n• 角色卡支持立绘图片，可自动用作对话背景\n• 导入 PNG 格式角色卡（tEXt chunk 解析）\n• 多用户资料，支持切换与独立人设\n• 每个 API 配置独立破墙提示词\n• Enter 键行为可选（发送 / 换行）\n• 新建对话向导（选 API / 角色卡 / 长记忆）\n• 图片背景暗度滑块\n• ZIP 全量备份 / 恢复\n• 导入导出分散到各页面 CommandBar\n• 角色卡多选导出模式\n• 多模态图片上传（OpenAI image_url）",
                "• OOBE setup wizard (API / Character / User)\n• 3-step character card wizard\n• Character art auto-set as chat background\n• PNG card import (tEXt chunk)\n• Multi-user profiles with personas\n• Per-API jailbreak prompts\n• Configurable Enter key behavior\n• New conversation wizard\n• Background dim slider\n• Full ZIP backup/restore\n• Import/export on each page's CommandBar\n• Multi-export character cards\n• Multimodal image upload (OpenAI image_url)");

            V110Bullets.Text = AppSettings.S("• 原生 CommandBar 替换自制底部工具栏\n• 实体返回键支持（HardwareButtons）\n• 深色模式 CommandBar 跟随主题\n• 启动行为选择（最近 / 新建 / 列表）\n• 新对话欢迎页\n• 对话预览 Markdown 符号过滤\n• 消息异步分片加载（性能优化）\n• 用户人设注入 System Prompt\n• 世界书图标 W10M 兼容修复",
                "• Native CommandBar replaces custom toolbar\n• Hardware back button support\n• Dark mode CommandBar follows theme\n• Startup behavior (recent/new/list)\n• Welcome page for new chats\n• Markdown filter in preview\n• Async message chunk loading\n• User persona in System Prompt\n• World Book icon W10M fix");

            V100Bullets.Text = AppSettings.S("• SplitView 汉堡导航\n• 流式 AI 对话 / Markdown 渲染\n• 对话分支导航\n• 角色卡 / 世界书 / API 配置管理\n• 长期记忆系统（自动总结 + 注入）\n• SillyTavern 格式导入导出\n• 对话外观个性化（背景 / 气泡颜色）",
                "• SplitView hamburger navigation\n• Streaming AI chat / Markdown render\n• Conversation branching\n• Character card / World Book / API config\n• Long-term memory (auto-summary + injection)\n• SillyTavern import/export\n• Chat appearance (background / bubble colors)");
        }

        private void BackButton_Click(object sender, RoutedEventArgs e)
        {
            if (Frame.CanGoBack) Frame.GoBack();
            else Frame.Navigate(typeof(SettingsPage));
        }

        private void OpenWebsiteButton_Click(object sender, RoutedEventArgs e)
        {
            var _ = Windows.System.Launcher.LaunchUriAsync(new Uri("https://github.com/nicekid1/Lumina.Roleplay"));
        }
    }
}
